### ISSUE TITLE
Allow `unset` as a spacing value

### ISSUE THREAD

**Issue by iansan5653** [primer/stylelint-config#437]
Currently `unset` is not an allowed value for `primer/spacing`, resulting in errors that cannot be resolved without a lint exception:

> Please use a primer size variable instead of 'unset'. Consult the primer docs for a suitable replacement. https://primer.style/foundations/primitives/size (primer/spacing)

Example:

```css
padding-bottom: unset;
```

**Comment by jonrohan** [comment]
Should be fixed in 13.0.0
